kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/hrittikhere/ci_stream/main

steps:
- name: test
  image: golang
  commands:
  - go mod init
  - go get
  - go test

  